<?php if (! defined('LP_THEME_DIR')) exit('No direct script access allowed');

// client area options

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_5f51fbe1b6e6b',
        'title' => esc_html__('Website settings', 'lptheme'),
        'fields' => array(
            array(
                'key' => 'field_5f5732f0f0f64',
                'label' => '<span class="dashicons dashicons-admin-home"></span> ' . esc_html__('General', 'lptheme'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_2f71c5d634634b1',
                'label' => esc_html__('General settings', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5f51fbfeaaaa4',
                'label' => esc_html__('Logo (.jpg, .png)', 'lptheme'),
                'name' => 'header_logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_svg5f51fbfa4',
                'label' => esc_html__('Logo SVG', 'lptheme'),
                'name' => 'header_logo_svg',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_faviconicon',
                'label' => esc_html__('Favicon.ico', 'lptheme'),
                'name' => 'favicon_ico',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_faviconsvg',
                'label' => esc_html__('Favicon.svg', 'lptheme'),
                'name' => 'favicon_svg',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),

            array(
                'key' => 'field_faviconapple180',
                'label' => esc_html__('Apple touch icon 180x180', 'lptheme'),
                'name' => 'apple_touch_180',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),

            array(
                'key' => 'field_5f5733293553f',
                'label' => '<span class="dashicons dashicons-phone"></span> ' . esc_html__('Contacts', 'lptheme'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f71c5d634634b3',
                'label' => esc_html__('Contacts', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5f6dcb4612d7d',
                'label' => esc_html__('Phone', 'lptheme') . ' 1',
                'name' => 'phone_1',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f6dcb7978a2d',
                'label' => esc_html__('Phone', 'lptheme') . ' 2',
                'name' => 'phone_2',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f6dcb7e78a2e',
                'label' => esc_html__('Phone', 'lptheme') . ' 3',
                'name' => 'phone_3',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_4f6dcb7ssg32e',
                'label' => esc_html__('Phone', 'lptheme') . ' 4',
                'name' => 'phone_4',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f5f277ff38fe',
                'label' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_5f6dcc2fd6904',
                'label' => esc_html__('Working hours', 'lptheme'),
                'name' => 'working_hours',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_sdgdrcc2fd69235',
                'label' => esc_html__('Addres', 'lptheme'),
                'name' => 'address',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'rows' => 4,
            ),
            array(
                'key' => 'field_sdg5d6334634b3',
                'label' => esc_html__('Socials', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_facebook8fe',
                'label' => '<span class="dashicons dashicons-facebook-alt"></span> Facebook',
                'name' => 'facebook_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_twitter8fe',
                'label' => '<span class="dashicons dashicons-twitter"></span> X',
                'name' => 'twitter_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_dasvd2435ff28fe',
                'label' => 'Telegram',
                'name' => 'telegram_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_sdbddf5ff28fe',
                'label' => '<span class="dashicons dashicons-whatsapp"></span> Viber',
                'name' => 'viber_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_instagram8fe',
                'label' => '<span class="dashicons dashicons-instagram"></span> Instagram',
                'name' => 'instagram_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_sdgd277ff28fe',
                'label' => 'VK',
                'name' => 'vk_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_linkedin8fe',
                'label' => '<span class="dashicons dashicons-linkedin"></span> Linkedin',
                'name' => 'linkedin_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_skype8fe',
                'label' => 'Skype',
                'name' => 'skype_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_tiktoksve',
                'label' => 'Tiktok',
                'name' => 'tiktok_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_youtubesve',
                'label' => 'YouTube',
                'name' => 'youtube_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_5f57854293553f',
                'label' => '<span class="dashicons dashicons-editor-code"></span> ' . esc_html__('Analytics', 'lptheme'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_3f72c5d634634b3',
                'label' => esc_html__('Analytics', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => esc_html__('Areas for displaying analytics code, metrics and other third-party scripts', 'lptheme'),
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_6f6dtgfde',
                'label' => esc_html__('Paste code before closing tag', 'lptheme') . ' <code>&lt;/head&gt;</code>',
                'name' => 'closing_head_code',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => esc_html__('your code', 'lptheme'),
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_2f6d7e56dtgfde',
                'label' => esc_html__('Insert code after opening tag', 'lptheme') . ' <code>&lt;body&gt;</code>',
                'name' => 'opening_body_code',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => esc_html__('your code', 'lptheme'),
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_1f6d7e5dta2e',
                'label' => esc_html__('Paste code before closing tag', 'lptheme') . ' <code>&lt;/body&gt;</code>',
                'name' => 'closing_body_code',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => esc_html__('your code', 'lptheme'),
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),

            // ADD THIS BEFORE THE ANALYTICS TAB IN YOUR EXISTING client-settings.php

            array(
                'key' => 'field_schema_tab553f',
                'label' => '<span class="dashicons dashicons-admin-site-alt3"></span> ' . esc_html__('Schema.org', 'lptheme'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_schema_message',
                'label' => esc_html__('Schema.org Structured Data', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => esc_html__('Configure structured data for better SEO. This data helps search engines understand your business.', 'lptheme'),
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_enable_schema',
                'label' => esc_html__('Enable Schema Markup', 'lptheme'),
                'name' => 'enable_schema',
                'type' => 'true_false',
                'instructions' => esc_html__('Turn on to add JSON-LD structured data to your website', 'lptheme'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => esc_html__('on', 'lptheme'),
                'ui_off_text' => esc_html__('off', 'lptheme'),
            ),
            array(
                'key' => 'field_schema_org_type',
                'label' => esc_html__('Organization Type', 'lptheme'),
                'name' => 'schema_org_type',
                'type' => 'select',
                'instructions' => esc_html__('Select the type that best describes your organization', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Organization' => esc_html__('Organization (General)', 'lptheme'),
                    'LocalBusiness' => esc_html__('Local Business', 'lptheme'),
                    'MedicalOrganization' => esc_html__('Medical Organization', 'lptheme'),
                    'Hospital' => esc_html__('Hospital', 'lptheme'),
                    'Dentist' => esc_html__('Dentist', 'lptheme'),
                    'MedicalClinic' => esc_html__('Medical Clinic', 'lptheme'),
                    'Store' => esc_html__('Store', 'lptheme'),
                    'Restaurant' => esc_html__('Restaurant', 'lptheme'),
                    'Hotel' => esc_html__('Hotel', 'lptheme'),
                    'ProfessionalService' => esc_html__('Professional Service', 'lptheme'),
                ),
                'default_value' => 'Organization',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_schema_legal_name',
                'label' => esc_html__('Legal Name', 'lptheme'),
                'name' => 'schema_legal_name',
                'type' => 'text',
                'instructions' => esc_html__('Official registered name of your organization', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_alternate_name',
                'label' => esc_html__('Alternate Name', 'lptheme'),
                'name' => 'schema_alternate_name',
                'type' => 'text',
                'instructions' => esc_html__('Alternative name or DBA (Doing Business As)', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '34',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_description',
                'label' => esc_html__('Organization Description', 'lptheme'),
                'name' => 'schema_description',
                'type' => 'textarea',
                'instructions' => esc_html__('Brief description of your organization (recommended 150-250 characters)', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_schema_founding_date',
                'label' => esc_html__('Founding Date', 'lptheme'),
                'name' => 'schema_founding_date',
                'type' => 'date_picker',
                'instructions' => esc_html__('Date when the organization was founded', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_schema_price_range',
                'label' => esc_html__('Price Range', 'lptheme'),
                'name' => 'schema_price_range',
                'type' => 'text',
                'instructions' => esc_html__('Price range (e.g., $$, $$$, or Low-High)', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '$$',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_vat_id',
                'label' => esc_html__('VAT ID / Tax ID', 'lptheme'),
                'name' => 'schema_vat_id',
                'type' => 'text',
                'instructions' => esc_html__('Tax identification number', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '34',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_location_divider',
                'label' => esc_html__('Location Details', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => esc_html__('Detailed address information for schema markup', 'lptheme'),
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_schema_street_address',
                'label' => esc_html__('Street Address', 'lptheme'),
                'name' => 'schema_street_address',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_postal_code',
                'label' => esc_html__('Postal Code', 'lptheme'),
                'name' => 'schema_postal_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_locality',
                'label' => esc_html__('City/Locality', 'lptheme'),
                'name' => 'schema_locality',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Odesa',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_region',
                'label' => esc_html__('Region/State', 'lptheme'),
                'name' => 'schema_region',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Odessa',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_country',
                'label' => esc_html__('Country Code', 'lptheme'),
                'name' => 'schema_country',
                'type' => 'text',
                'instructions' => esc_html__('Two-letter country code (ISO 3166-1 alpha-2)', 'lptheme'),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'UA',
                'placeholder' => 'UA',
                'prepend' => '',
                'append' => '',
                'maxlength' => 2,
            ),
            array(
                'key' => 'field_schema_geo_coordinates',
                'label' => esc_html__('Geographic Coordinates', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => esc_html__('Add latitude and longitude for better local SEO', 'lptheme'),
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_schema_latitude',
                'label' => esc_html__('Latitude', 'lptheme'),
                'name' => 'schema_latitude',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '46.4825',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_longitude',
                'label' => esc_html__('Longitude', 'lptheme'),
                'name' => 'schema_longitude',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '30.7233',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_schema_opening_hours',
                'label' => esc_html__('Opening Hours Specification', 'lptheme'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => esc_html__('Structured opening hours for search engines', 'lptheme'),
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_schema_opening_hours_spec',
                'label' => esc_html__('Opening Hours', 'lptheme'),
                'name' => 'schema_opening_hours_spec',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_enable_schema',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => esc_html__('Add Hours', 'lptheme'),
                'sub_fields' => array(
                    array(
                        'key' => 'field_schema_day_of_week',
                        'label' => esc_html__('Day of Week', 'lptheme'),
                        'name' => 'day_of_week',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Monday' => esc_html__('Monday', 'lptheme'),
                            'Tuesday' => esc_html__('Tuesday', 'lptheme'),
                            'Wednesday' => esc_html__('Wednesday', 'lptheme'),
                            'Thursday' => esc_html__('Thursday', 'lptheme'),
                            'Friday' => esc_html__('Friday', 'lptheme'),
                            'Saturday' => esc_html__('Saturday', 'lptheme'),
                            'Sunday' => esc_html__('Sunday', 'lptheme'),
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_schema_opens',
                        'label' => esc_html__('Opens', 'lptheme'),
                        'name' => 'opens',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'H:i:s',
                        'return_format' => 'H:i:s',
                    ),
                    array(
                        'key' => 'field_schema_closes',
                        'label' => esc_html__('Closes', 'lptheme'),
                        'name' => 'closes',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'H:i:s',
                        'return_format' => 'H:i:s',
                    ),
                ),
            ),

        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'customers-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
